apiVersion: v1
kind: Namespace
metadata:
  name: my-smack
---
kind: Service
apiVersion: v1
metadata:
  name: smackapi
  namespace: my-smack
spec:
  selector:
    app: my-smackapi
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8081
  type: LoadBalancer
---
kind: Service
apiVersion: v1
metadata:
  name: smackweb
  namespace: my-smack
spec:
  selector:
    app: my-smackweb
  ports:
  - protocol: TCP
    port: 8082
    targetPort: 8082
  type: LoadBalancer
---
kind: Deployment
apiVersion: apps/v1beta1 # for versions before 1.6.0 use extensions/v1beta1
metadata:
  name: my-smackapideploy
  namespace: my-smack
  labels:
    zone: prod
    version: v1
spec:
  replicas: 3
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: my-smackapi
    spec:
      containers:
      - name: my-smackapi
        image: keithcontainerregistry.azurecr.io/chzbrgr71/smackapi:latest
        ports:
        - containerPort: 8081
---
kind: Deployment
apiVersion: apps/v1beta1 # for versions before 1.6.0 use extensions/v1beta1
metadata:
  name: my-smackwebdeploy
  namespace: my-smack
  labels:
    zone: prod
    version: v1
spec:
  replicas: 3
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: my-smackweb
    spec:
      containers:     
      - name: my-smackweb
        image: keithcontainerregistry.azurecr.io/chzbrgr71/smackweb:latest        
        ports:
        - containerPort: 8082
