apiVersion: v1
kind: Namespace
metadata:
  name: my-ns
---
kind: Service
apiVersion: v1
metadata:
  name: my-healthysvc
  namespace: my-ns
spec:
  selector:
    app: my-app
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: LoadBalancer
---
kind: Deployment
apiVersion: apps/v1beta1 # for versions before 1.6.0 use extensions/v1beta1
metadata:
  name: my-healthydeploy
  namespace: my-ns
  labels:
    zone: prod
    version: v1
spec:
  replicas: 3
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-ctr2
        image: evillgenius/kuar:1
        livenessProbe:
          httpGet:
            path: /healthy
            port: 8080
          initialDelaySeconds: 5
          timeoutSeconds: 1
          periodSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          periodSeconds: 2
          initialDelaySeconds: 0
          failureThreshold: 3
          successThreshold: 1
        ports:
        - containerPort: 8080
