kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1alpha1
metadata:
  name: briar_cluster-admin
subjects:
  - kind: User # May be "User", "Group" or "ServiceAccount"
    name: '{fill in}'
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io